Repository Mirai-X-Devs/officialweb, pull requests merged in 2024-03, with the labels that each got.

#34 feat: project structure
  README.md
  index.html
  package-lock.json
  package.json
  postcss.config.js
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  tailwind.config.js
  vite.config.js
Labels: enhancement

#35 feat: add tailwindcss theme
  src/App.css
  src/App.jsx
  tailwind.config.js
Labels: enhancement

#36 feat: add css index style
  src/App.jsx
  src/index.css
Labels: enhancement

#38 Revert "feat: clear code and add react router dom"
  index.html
  package-lock.json
  package.json
  src/main.jsx
Labels: bug, enhancement

#39 fix: delect deafault asstest
  src/assets/react.svg
Labels: bug

#42 feat: add button components
  src/components/Button.jsx
Labels: enhancement

#43 feat: add design folder and Benefits component
  src/components/design/Benefits.jsx
Labels: enhancement

#44 feat: add collaboration component
  src/components/design/Collaboration.jsx
Labels: enhancement

#45 feat: add header component
  src/components/design/Header.jsx
Labels: enhancement

#46 feat: add hero component
  src/components/design/Hero.jsx
Labels: enhancement

#47 feat: add pricing components
  src/components/design/Pricing.jsx
Labels: enhancement

#48 feat: add Roadmap components
  src/components/design/Roadmap.jsx
Labels: enhancement

#49 feat: add benefits section
  src/components/Benefits.jsx
  src/components/design/Services.jsx
Labels: enhancement

#51 Revert "feat: add pricing components"
  src/components/design/Pricing.jsx
Labels: bug

#52 feat: add collaboration section
  src/components/Collaboration.jsx
Labels: enhancement

#54 feat: add company logo section
  src/components/CompanyLogo.jsx
Labels: enhancement

#56 feat: add footer section
  src/components/Footer.jsx
Labels: enhancement

#58 ·feat: add generationg section
  src/components/Generating.jsx
Labels: enhancement

#60 feat: add header section
  src/components/Header.jsx
Labels: enhancement

#62 feat: add heading section
  src/components/Heading.jsx
Labels: enhancement

#64 feat: add hero section
  src/components/Hero.jsx
Labels: enhancement

#66 feat: add notification section
  src/components/Notification.jsx
Labels: enhancement

#68 feat: add pricing section
  src/components/Pricing.jsx
Labels: enhancement

#72 feat: add roadmap section
  src/components/Roadmap.jsx
Labels: enhancement

#74 feat: add section svg
  src/components/Section.jsx
Labels: enhancement

#76 feat: add services section
  src/components/Services.jsx
Labels: enhancement

#78 feat: add tagline section
  src/components/Tagline.jsx
Labels: enhancement

#80 feat: add constants
  src/constants/index.js
Labels: enhancement

#82 fix: update app file with new components
  src/App.jsx
Labels: enhancement

#84 fix: update index.html and dependency files
  index.html
  package.json
Labels: bug

#86 fixed: indexed files
  LICENSE
  README.md
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/Benefits.jsx
  src/components/Collaboration.jsx
  src/components/CompanyLogos.jsx
  src/components/Footer.jsx
  src/components/Generating.jsx
  src/components/Header.jsx
  src/components/Heading.jsx
  src/components/Hero.jsx
  src/components/Notification.jsx
  src/components/Pricing.jsx
  src/components/PricingList.jsx
  src/components/Roadmap.jsx
  src/components/Section.jsx
  src/components/Services.jsx
  src/components/design/Benefits.jsx
  src/components/design/Collaboration.jsx
  src/components/design/Header.jsx
  src/components/design/Hero.jsx
  src/components/design/Pricing.jsx
  src/constants/index.js
  src/main.jsx
  tailwind.config.js
Labels: bug, duplicate, wontfix

#88 fix:hedear and hero section
  index.html
  package-lock.json
  package.json
  src/assets/academic.svg
  src/assets/background.jpeg
  src/assets/background.jpg
  src/assets/background.jpga
  src/assets/docs.svg
  src/assets/events.svg
  src/assets/favicon.png
  src/assets/hero/curve.png
  src/assets/hero/robost.jpg
  src/assets/hero/robot.jpg
  src/assets/index.js
  src/assets/miraidev-logo.png
  src/assets/notification/image-1.png
  src/assets/notification/image-2.png
  src/assets/notification/image-3.png
  src/assets/notification/image-4.png
  src/assets/sponsored.svg
  src/assets/svg/ButtonGradient.jsx
  src/components/Collaboration.jsx
  src/components/Generating.jsx
  src/components/Header.jsx
  src/components/Hero.jsx
  src/components/Notification.jsx
  src/components/design/Header.jsx
  src/components/design/Hero.jsx
  src/constants/index.js
  tailwind.config.js
Labels: bug
